// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yezvprfvcrxzmlysruco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllenZwcmZ2Y3J4em1seXNydWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mzg0ODIsImV4cCI6MjA2NDIxNDQ4Mn0.iatmdtbo5LgUE90KHSEC05rF_HBO4bANdYQrNIW3UO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});